### ISSUE TITLE
Issue downloading invoice with PF set as payment method

### ISSUE THREAD

**Issue by Linuc82** [Payfast/mod-whmcs#11]
Clients who have invoices that have PayFast set as payment method report that they are unable to download invoices from the WHMCS client area.

Returns error:

The webpage at https://www.domain.co.za/dl.php?type=i&id=919626 might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by eugenefvdm** [comment]
Hi @Linuc82 

I would try first examining the server's error log for 500 errors. The response you're getting is most likely a server error and typically a server will show something in it's log file.

**Comment by Linuc82** [comment]
Hi @eugenefvdm 

We checked Apache logs and error logs.

This error only happens when a client has PayFast set as Payment Method on the invoice.  If we change it to any other payment method (EFT, PayPal, Stripe etc), the clients can download the invoices fine, but set it to PayFast and they will get the error provided above.

**Comment by eugenefvdm** [comment]
Hi again @Linuc82 

Can you paste the error in the Apache log when you download a Payfast invoice?

**Comment by Linuc82** [comment]
Hi @eugenefvdm 

Nothing is reported in the webserver logs, the error is displayed on the browser when clients try to download PayFast invoices.

We tailed the logs, nothing shows up, so it's not web server related.

**Comment by eugenefvdm** [comment]
Hi @Linuc82 

It has to be something specific to your environment. The error comes from your server. I'm surprised you see nothing in the log, perhaps error reporting isn't set on? The log should at least show HTTP code 200 if not 500.

Anyhow, I just want to state I don't work for Payfast. I'm merely an experienced Linux engineer and WHMCS person that has multiple installations with that module working perfectly. Some of those installations are running for years and have been upgraded multiple times. So yes, maybe something with the way Payfast is installed and your environment, but unlikely exactly to do with the Payfast module itself.

Anyway happy if you want me to help  ree of charge, you can contact me on +27 82 309-6710. It will most like require screen sharing or Anydesk access. Otherwise I guess log a ticket with Payfast or hope someone comes to see what's going on in the issue tracker. This isn't exactly a busy forum.

Good luck! All the best.

**Comment by appinlet** [comment]
Thanks @eugenefvdm; we concur with your assessment that this is more likely a server error than an issue with the module based on the information provided.

@Linuc82, please kindly submit a ticket at https://support.payfast.help/portal/en/newticket, and our team will do our best to assist in a secure manner.
